title: SONG ZHOU
email: songzhou21@outlook.com
description: >- # this means to ignore newlines until "baseurl:"
    I wouldn't drink the coffee. Always tasted like boiled dirt.
baseurl: "" # the subpath of your site, e.g. /blog
url: "https://songzhou21.github.io"
twitter_username: songzhou21
github_username:  songzhou21

# Build settings
markdown: kramdown
theme: minima
plugins:
  - jekyll-feed